@extends('layouts.app')

@section('title', 'Reports')
@section('page-title', 'Reports')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
    <form class="d-flex gap-2" method="GET">
        <select name="type" class="form-select form-select-sm">
            <option value="">All Types</option>
            <option value="daily">Daily</option>
            <option value="weekly">Weekly</option>
            <option value="monthly">Monthly</option>
            <option value="session">Session</option>
            <option value="custom">Custom (Instructor)</option>
        </select>
        <button class="btn btn-sm btn-outline-secondary">Filter</button>
    </form>
    <a href="{{ route('admin.reports.generate') }}" class="btn btn-sm btn-primary">
        <i class="bi bi-plus-lg me-1"></i>Generate Report
    </a>
</div>

<div class="card">
    <div class="table-responsive">
        <table class="table table-hover mb-0">
            <thead class="table-light">
                <tr>
                    <th>Title</th>
                    <th>Type</th>
                    <th>Period</th>
                    <th>Generated By</th>
                    <th>Status</th>
                    <th>Date</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @forelse($reports as $report)
                <tr>
                    <td class="fw-medium">{{ $report->title }}</td>
                    <td><span class="badge bg-secondary">{{ ucfirst($report->type) }}</span></td>
                    <td class="text-muted small">
                        {{ $report->period_start?->format('d M Y') }} –
                        {{ $report->period_end?->format('d M Y') }}
                    </td>
                    <td class="text-muted small">{{ $report->generatedBy->name ?? '—' }}</td>
                    <td>
                        <span class="badge bg-{{ $report->status === 'ready' ? 'success' : ($report->status === 'generating' ? 'warning' : 'danger') }}">
                            {{ ucfirst($report->status) }}
                        </span>
                    </td>
                    <td class="text-muted small">{{ $report->created_at->format('d M Y H:i') }}</td>
                    <td>
                        <a href="{{ route('admin.reports.show', $report) }}" class="btn btn-sm btn-outline-primary">View</a>
                    </td>
                </tr>
                @empty
                <tr><td colspan="7" class="text-center text-muted py-4">No reports yet.</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
    <div class="card-footer">{{ $reports->links() }}</div>
</div>
@endsection
