@extends('layouts.app')

@section('title', $report->title)
@section('page-title', 'Report Detail')

@section('content')
<div class="d-flex justify-content-between align-items-start mb-3">
    <div>
        <h5 class="mb-1">{{ $report->title }}</h5>
        <small class="text-muted">
            Generated by {{ $report->generatedBy->name ?? '—' }} on {{ $report->created_at->format('d M Y H:i') }}
        </small>
    </div>
    <a href="{{ route('admin.reports.index') }}" class="btn btn-sm btn-outline-secondary">← Back</a>
</div>

@php $data = $report->data; @endphp

@if(isset($data['summary']))
<div class="card mb-3">
    <div class="card-header bg-transparent">
        <h6 class="mb-0">Session Summary</h6>
    </div>
    <div class="card-body">
        <div class="row g-3">
            <div class="col-sm-6 col-lg-3">
                <div class="p-3 bg-light rounded">
                    <div class="small text-muted">Overall Status</div>
                    <div class="fw-bold text-capitalize">{{ str_replace('_', ' ', $data['summary']['overall_status'] ?? 'n/a') }}</div>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3">
                <div class="p-3 bg-light rounded">
                    <div class="small text-muted">Attendance Rate</div>
                    <div class="fw-bold">{{ $data['summary']['attendance_rate'] ?? 0 }}%</div>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3">
                <div class="p-3 bg-light rounded">
                    <div class="small text-muted">Dead Air</div>
                    <div class="fw-bold">{{ $data['summary']['total_dead_air_seconds'] ?? 0 }}s</div>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3">
                <div class="p-3 bg-light rounded">
                    <div class="small text-muted">Critical Alerts</div>
                    <div class="fw-bold">{{ $data['summary']['critical_alerts'] ?? 0 }}</div>
                </div>
            </div>
        </div>

        @if(!empty($data['recommendations']))
            <div class="mt-3">
                <div class="small text-muted mb-2">Recommendations</div>
                <ul class="mb-0">
                    @foreach($data['recommendations'] as $recommendation)
                        <li>{{ $recommendation }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
</div>
@endif

<div class="row g-3">
    @if(isset($data['sessions']))
    <div class="col-md-3">
        <div class="card text-center p-3">
            <div class="fs-1 fw-bold text-primary">{{ $data['sessions']['total'] ?? 0 }}</div>
            <small class="text-muted">Total Sessions</small>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card text-center p-3">
            <div class="fs-1 fw-bold text-success">{{ $data['sessions']['completed'] ?? 0 }}</div>
            <small class="text-muted">Completed</small>
        </div>
    </div>
    @endif

    @if(isset($data['behavior']))
    <div class="col-md-3">
        <div class="card text-center p-3">
            <div class="fs-1 fw-bold text-danger">{{ $data['behavior']['negative'] ?? $data['behavior']['negative_incidents'] ?? 0 }}</div>
            <small class="text-muted">Negative Speech</small>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card text-center p-3">
            <div class="fs-1 fw-bold text-success">{{ $data['behavior']['positive'] ?? $data['behavior']['positive_incidents'] ?? 0 }}</div>
            <small class="text-muted">Positive Speech</small>
        </div>
    </div>
    @endif
</div>

<div class="card mt-3">
    <div class="card-header"><h6 class="mb-0">Full Report Data</h6></div>
    <div class="card-body">
        <pre class="mb-0" style="font-size:.8rem">{{ json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre>
    </div>
</div>
@endsection
