@extends('layouts.app')

@section('title', $report->title)
@section('page-title', 'Report Detail')

@section('content')
@php $data = $report->data ?? []; @endphp

<div class="d-flex justify-content-between align-items-start mb-3">
    <div>
        <h5 class="mb-1">{{ $report->title }}</h5>
        <small class="text-muted">
            Generated by {{ $report->generatedBy->name ?? 'N/A' }} on {{ $report->created_at->format('d M Y H:i') }}
        </small>
    </div>
    <div class="d-flex gap-2 no-print">
        <button onclick="window.print()" class="btn btn-sm btn-primary">
            <i class="bi bi-printer me-1"></i> Print
        </button>
        <a href="{{ $backRoute ?? route('admin.reports.index') }}" class="btn btn-sm btn-outline-secondary">Back</a>
    </div>
</div>

@if(isset($data['summary']))
    <div class="card mb-3">
        <div class="card-header bg-transparent">
            <h6 class="mb-0">Session Summary</h6>
        </div>
        <div class="card-body">
            <div class="row g-3">
                <div class="col-sm-6 col-lg-3">
                    <div class="p-3 bg-light rounded">
                        <div class="small text-muted">Overall Status</div>
                        <div class="fw-bold text-capitalize">{{ str_replace('_', ' ', $data['summary']['overall_status'] ?? 'n/a') }}</div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="p-3 bg-light rounded">
                        <div class="small text-muted">Attendance Rate</div>
                        <div class="fw-bold">{{ $data['summary']['attendance_rate'] ?? 0 }}%</div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="p-3 bg-light rounded">
                        <div class="small text-muted">Dead Air</div>
                        <div class="fw-bold">{{ $data['summary']['total_dead_air_seconds'] ?? 0 }}s</div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="p-3 bg-light rounded">
                        <div class="small text-muted">Critical Alerts</div>
                        <div class="fw-bold">{{ $data['summary']['critical_alerts'] ?? 0 }}</div>
                    </div>
                </div>
            </div>

            @if(!empty($data['recommendations']))
                <div class="mt-3">
                    <div class="small text-muted mb-2">Recommendations</div>
                    <ul class="mb-0">
                        @foreach($data['recommendations'] as $recommendation)
                            <li>{{ $recommendation }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
    </div>
@endif

@if(isset($data['session']))
    <div class="card mb-3">
        <div class="card-header bg-transparent">
            <h6 class="mb-0">Session Information</h6>
        </div>
        <div class="card-body">
            <div class="row g-3">
                <div class="col-md-4">
                    <div class="small text-muted">Course</div>
                    <div class="fw-semibold">{{ $data['session']['course'] ?? 'N/A' }}</div>
                </div>
                <div class="col-md-4">
                    <div class="small text-muted">Instructor</div>
                    <div class="fw-semibold">{{ $data['session']['instructor'] ?? 'N/A' }}</div>
                </div>
                <div class="col-md-4">
                    <div class="small text-muted">Duration</div>
                    <div class="fw-semibold">{{ $data['session']['duration'] ?? 0 }} minutes</div>
                </div>
            </div>
        </div>
    </div>
@endif

<div class="row g-3">
    @if(isset($data['sessions']))
        <div class="col-md-3">
            <div class="card text-center p-3">
                <div class="fs-1 fw-bold text-primary">{{ $data['sessions']['total'] ?? 0 }}</div>
                <small class="text-muted">Total Sessions</small>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center p-3">
                <div class="fs-1 fw-bold text-success">{{ $data['sessions']['completed'] ?? 0 }}</div>
                <small class="text-muted">Completed</small>
            </div>
        </div>
    @endif

    @if(isset($data['behavior']))
        <div class="col-md-3">
            <div class="card text-center p-3">
                <div class="fs-1 fw-bold text-danger">{{ $data['behavior']['negative'] ?? $data['behavior']['negative_incidents'] ?? 0 }}</div>
                <small class="text-muted">Negative Speech</small>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center p-3">
                <div class="fs-1 fw-bold text-success">{{ $data['behavior']['positive'] ?? $data['behavior']['positive_incidents'] ?? 0 }}</div>
                <small class="text-muted">Positive Speech</small>
            </div>
        </div>
    @endif
</div>

@if(!empty($data['attendance']['students']))
    <div class="card mt-3">
        <div class="card-header"><h6 class="mb-0">Attendance</h6></div>
        <div class="table-responsive">
            <table class="table align-middle mb-0">
                <thead>
                    <tr>
                        <th>Student</th>
                        <th>Status</th>
                        <th>Joined</th>
                        <th>Left</th>
                        <th>Minutes</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data['attendance']['students'] as $student)
                        <tr>
                            <td>{{ $student['student'] ?? 'Unknown' }}</td>
                            <td><span class="badge bg-light text-muted border">{{ $student['status'] ?? 'N/A' }}</span></td>
                            <td>{{ $student['joined_at'] ?? '-' }}</td>
                            <td>{{ $student['left_at'] ?? '-' }}</td>
                            <td>{{ $student['duration_minutes'] ?? '-' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endif

@if(!empty($data['behavior']['incidents']))
    <div class="card mt-3">
        <div class="card-header"><h6 class="mb-0">Behavior Incidents</h6></div>
        <div class="table-responsive">
            <table class="table align-middle mb-0">
                <thead>
                    <tr>
                        <th>User</th>
                        <th>Type</th>
                        <th>Phrase</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data['behavior']['incidents'] as $incident)
                        <tr>
                            <td>{{ $incident['user'] ?? 'Unknown' }}</td>
                            <td><span class="badge bg-light text-muted border">{{ str_replace('_', ' ', $incident['type'] ?? 'N/A') }}</span></td>
                            <td>{{ $incident['detected_phrase'] ?? '-' }}</td>
                            <td>{{ $incident['timestamp_seconds'] ?? 0 }}s</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endif

@if(!empty($data['data_leakage']['incidents']))
    <div class="card mt-3">
        <div class="card-header"><h6 class="mb-0">Data Leakage Incidents</h6></div>
        <div class="table-responsive">
            <table class="table align-middle mb-0">
                <thead>
                    <tr>
                        <th>User</th>
                        <th>Channel</th>
                        <th>Type</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data['data_leakage']['incidents'] as $incident)
                        <tr>
                            <td>{{ $incident['user'] ?? 'Unknown' }}</td>
                            <td>{{ strtoupper($incident['channel'] ?? 'N/A') }}</td>
                            <td>{{ str_replace('_', ' ', $incident['leakage_type'] ?? 'N/A') }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endif

<div class="card mt-3 no-print">
    <div class="card-header"><h6 class="mb-0">Full Report Data</h6></div>
    <div class="card-body">
        <pre class="mb-0" style="font-size:.8rem">{{ json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre>
    </div>
</div>
@endsection

@push('styles')
<style>
@media print {
    .sidebar,
    .topbar,
    .no-print {
        display: none !important;
    }

    .main-content {
        margin-left: 0 !important;
    }

    .content-area {
        padding: 0 !important;
    }

    body {
        background: #fff !important;
    }

    .card {
        box-shadow: none !important;
        break-inside: avoid;
    }
}
</style>
@endpush
